spring:
  application:
    name: shortener-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 3000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: 43.139.1.172
    port: 6379
    timeout: 2000
    lettuce:
      pool:
        max-active: 8
        max-idle: 4

# 自定义配置
shortener:
  base-url: https://43.139.1.172:8080/
  bloom-filter:
    capacity: 10000000   # 布隆过滤器容量
    false-positive-rate: 0.001 # 误判率
  snowflake:
    datacenter-id: 1

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
      show-details: always