name: Deploy to Tencent Lighthouse
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate .env
        run: |
          echo "MYSQL_PORT=${{ secrets.SL_MYSQL_PORT }}" > .env
          echo "DATABASE_NAME=${{ secrets.SL_DATABASE_NAME }}" > .env
          echo "DATABASE_USERNAME=${{ secrets.SL_DATABASE_USERNAME }}" > .env
          echo "DATABASE_PASSWORD=${{ secrets.SL_DATABASE_PASSWORD }}" > .env
          echo "REDIS_PORT=${{ secrets.SL_REDIS_PORT }}" > .env
          echo "REDIS_PASSWORD=${{ secrets.SL_REDIS_PASSWORD }}" > .env
          echo "RABBITMQ_PORT=${{ secrets.SL_RABBITMQ_PORT }}" > .env
          echo "RABBITMQ_USERNAME=${{ secrets.SL_RABBITMQ_USERNAME }}" > .env
          echo "RABBITMQ_PASSWORD=${{ secrets.SL_RABBITMQ_PASSWORD }}" > .env
        shell: bash

      - name: Deploy via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PASSWORD }}
          source: "./*"
          target: "/data/EZTools/ShortLink"
