name: Production Deployment

on:
  push:
    branches:
      - master  # 触发分支

env:
  DEPLOY_DIR: /root/data/EZTools/ShortLink  # 服务器部署路径

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      # 步骤1：检出代码
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 步骤2.1：预配置 SSH 环境
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          # 强制添加服务器指纹（绕过首次确认）
          ssh-keyscan -p ${{ secrets.SSH_PORT || 22 }} ${{ secrets.SERVER_PUBLIC_IP }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          # 写入私钥并设置严格权限
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      # 步骤3：安全传输文件
      - name: Transfer files via rsync
        run: |
          rsync -avz \
          -e "ssh -p ${{ secrets.SSH_PORT }} -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" \
          --rsync-path="sudo rsync" \  # 确保 rsync 有权限写入目标目录
          --exclude={.git,.github,node_modules} \
          ./ \
          root@${{ secrets.SERVER_PUBLIC_IP }}:${{ env.DEPLOY_DIR }}/

      # 步骤4：安全部署服务
      - name: Deploy services
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_PUBLIC_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # 创建必要目录（无需修改权限）
            mkdir -p $DEPLOY_DIR/var/lib/{nginx,mysql,redis,rabbitmq}
            mkdir -p $DEPLOY_DIR/backend/src/main/resources/DataBase
            
            # 加载环境变量
            export SERVER_PRIVATE_IP=${{ secrets.SERVER_PRIVATE_IP }}
            export SERVER_PUBLIC_IP=${{ secrets.SERVER_PUBLIC_IP }}
            export MYSQL_PORT=${{ secrets.SL_MYSQL_PORT }}
            export DATABASE_NAME=${{ secrets.SL_DATABASE_NAME }}
            export DATABASE_USERNAME=${{ secrets.SL_DATABASE_USERNAME }}
            export DATABASE_PASSWORD=${{ secrets.SL_DATABASE_PASSWORD }}
            export REDIS_PORT=${{ secrets.SL_REDIS_PORT }}
            export REDIS_PASSWORD=${{ secrets.SL_REDIS_PASSWORD }}
            export RABBITMQ_PORT=${{ secrets.SL_RABBITMQ_PORT }}
            export RABBITMQ_USERNAME=${{ secrets.SL_RABBITMQ_USERNAME }}
            export RABBITMQ_PASSWORD=${{ secrets.SL_RABBITMQ_PASSWORD }}
            
            # 同步初始化脚本
            rsync -avz $DEPLOY_DIR/backend/src/main/resources/DataBase/init_scripts.sql \
            $DEPLOY_DIR/backend/src/main/resources/DataBase/init_scripts.sql      
            
            # 进入部署目录
            cd $DEPLOY_DIR
            # 强制清理旧容器和镜像
            docker-compose down --volumes --rmi all
            # 重建服务（避免缓存问题）
            docker-compose up -d --build --force-recreate --remove-orphans
            # 清理无用资源
            docker system prune -af
            docker volume prune -f