- name: Test SSH Access
  uses: appleboy/ssh-action@v1.0.0
  with:
    host: ${{ secrets.SERVER_PUBLIC_IP }}
    username: ${{ secrets.SERVER_USERNAME }}
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    script: |
      echo "连接成功！"
      exit 0